@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package chiefarug.mods.complete_compost.compat;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;