@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package chiefarug.mods.complete_compost;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;